name: 'Ally Accessibility Scanner'
description: 'Scan your codebase for accessibility violations using axe-core'
author: 'Liz Fong-Jones'
branding:
  icon: 'eye'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan (default: current directory)'
    required: false
    default: '.'
  threshold:
    description: 'Maximum allowed violations before failing (default: 0)'
    required: false
    default: '0'
  url:
    description: 'URL to scan instead of files'
    required: false
  output:
    description: 'Output directory for reports'
    required: false
    default: '.ally'
  max-files:
    description: 'Limit scan to first N files (useful for large projects)'
    required: false
  baseline:
    description: 'Set current scan as baseline for future comparison'
    required: false
    default: 'false'
  compare-baseline:
    description: 'Compare against saved baseline and check for regressions'
    required: false
    default: 'false'
  fail-on-regression:
    description: 'Fail the workflow if accessibility regresses from baseline'
    required: false
    default: 'false'

outputs:
  score:
    description: 'Accessibility score (0-100)'
    value: ${{ steps.scan.outputs.score }}
  violations:
    description: 'Total number of violations found'
    value: ${{ steps.scan.outputs.violations }}
  report:
    description: 'Path to the generated report'
    value: ${{ steps.scan.outputs.report }}
  improved:
    description: 'Number of files with improved accessibility (baseline mode)'
    value: ${{ steps.scan.outputs.improved }}
  regressed:
    description: 'Number of files with regressed accessibility (baseline mode)'
    value: ${{ steps.scan.outputs.regressed }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install ally
      shell: bash
      run: npm install -g ally-a11y

    - name: Run accessibility scan
      id: scan
      shell: bash
      run: |
        # Build the scan command
        SCAN_CMD="ally scan"
        
        # Add path or URL
        if [ -n "${{ inputs.url }}" ]; then
          SCAN_CMD="$SCAN_CMD --url ${{ inputs.url }}"
        else
          SCAN_CMD="$SCAN_CMD ${{ inputs.path }}"
        fi
        
        # Add max-files if specified (for large projects)
        if [ -n "${{ inputs.max-files }}" ]; then
          SCAN_CMD="$SCAN_CMD --max-files ${{ inputs.max-files }}"
        fi
        
        # Add baseline option if set
        if [ "${{ inputs.baseline }}" = "true" ]; then
          SCAN_CMD="$SCAN_CMD --baseline"
        fi
        
        # Add baseline comparison if enabled
        if [ "${{ inputs.compare-baseline }}" = "true" ]; then
          SCAN_CMD="$SCAN_CMD --compare-baseline"
        fi
        
        # Add fail-on-regression if enabled
        if [ "${{ inputs.fail-on-regression }}" = "true" ]; then
          SCAN_CMD="$SCAN_CMD --fail-on-regression"
        fi
        
        # Add standard output directory
        SCAN_CMD="$SCAN_CMD -o ${{ inputs.output }} --json"
        
        # Run the scan (use || true to capture output even if it fails)
        eval "$SCAN_CMD" > scan-output.json 2>&1 || SCAN_EXIT=$?
        
        # Extract results from scan output
        SCORE=$(cat "${{ inputs.output }}/scan.json" | jq -r '.summary.score // 0')
        VIOLATIONS=$(cat "${{ inputs.output }}/scan.json" | jq -r '.summary.totalViolations // 0')
        
        echo "score=$SCORE" >> $GITHUB_OUTPUT
        echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
        echo "report=${{ inputs.output }}/scan.json" >> $GITHUB_OUTPUT
        
        # If comparing baselines, extract improvement metrics
        if [ "${{ inputs.compare-baseline }}" = "true" ]; then
          IMPROVED=$(grep -oP 'Improved:\s*\K\d+' scan-output.json 2>/dev/null || echo "0")
          REGRESSED=$(grep -oP 'Regressed:\s*\K\d+' scan-output.json 2>/dev/null || echo "0")
          echo "improved=$IMPROVED" >> $GITHUB_OUTPUT
          echo "regressed=$REGRESSED" >> $GITHUB_OUTPUT
          
          # Show baseline comparison in output
          echo "ðŸ“Š Baseline Comparison:"
          echo "  âœ… Improved files: $IMPROVED"
          echo "  âš ï¸ Regressed files: $REGRESSED"
        fi
        
        # Check if scan failed due to threshold
        if [ -n "$SCAN_EXIT" ] && [ $SCAN_EXIT -ne 0 ]; then
          echo "::error::Accessibility scan failed with exit code $SCAN_EXIT"
          
          # Additional error info on regression
          if [ "${{ inputs.fail-on-regression }}" = "true" ]; then
            echo "::error::Regressions detected in accessibility baseline comparison"
          fi
          
          exit $SCAN_EXIT
        fi
        
        # Manual threshold check if regression gate not used
        if [ "${{ inputs.fail-on-regression }}" != "true" ] && [ "$VIOLATIONS" -gt "${{ inputs.threshold }}" ]; then
          echo "::error::Accessibility check failed: $VIOLATIONS violations exceed threshold of ${{ inputs.threshold }}"
          exit 1
        fi

    - name: Generate report artifact
      shell: bash
      run: ally report -o "${{ inputs.output }}/ACCESSIBILITY.md"
      
    - name: Comment on PR with results
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        SCORE=${{ steps.scan.outputs.score }}
        VIOLATIONS=${{ steps.scan.outputs.violations }}
        IMPROVED=${{ steps.scan.outputs.improved }}
        REGRESSED=${{ steps.scan.outputs.regressed }}
        
        # Build comment with results
        {
          echo "## â™¿ Accessibility Report"
          echo ""
          echo "Score: \`$SCORE/100\`"
          echo "Violations: \`$VIOLATIONS\`"
          echo ""
          
          if [ -n "$IMPROVED" ] && [ "$IMPROVED" -gt 0 ]; then
            echo "âœ… Improved: $IMPROVED files"
          fi
          
          if [ -n "$REGRESSED" ] && [ "$REGRESSED" -gt 0 ]; then
            echo "âš ï¸ Regressed: $REGRESSED files"
          fi
        } > /tmp/comment.txt
        
        # Post to PR if possible
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN not available, skipping PR comment"
        else
          cat /tmp/comment.txt
        fi