name: 'Ally Accessibility Scanner'
description: 'Scan your codebase for accessibility violations using axe-core'
author: 'Liz Fong-Jones'
branding:
  icon: 'eye'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan (default: current directory)'
    required: false
    default: '.'
  threshold:
    description: 'Maximum allowed violations before failing (default: 0)'
    required: false
    default: '0'
  url:
    description: 'URL to scan instead of files'
    required: false
  output:
    description: 'Output directory for reports'
    required: false
    default: '.ally'

outputs:
  score:
    description: 'Accessibility score (0-100)'
  violations:
    description: 'Total number of violations found'
  report:
    description: 'Path to the generated report'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install ally
      shell: bash
      run: npm install -g ally-a11y

    - name: Run accessibility scan
      id: scan
      shell: bash
      run: |
        if [ -n "${{ inputs.url }}" ]; then
          ally scan --url "${{ inputs.url }}" --threshold ${{ inputs.threshold }} -o "${{ inputs.output }}" --json > scan-output.json 2>&1 || true
        else
          ally scan "${{ inputs.path }}" --threshold ${{ inputs.threshold }} -o "${{ inputs.output }}" --json > scan-output.json 2>&1 || true
        fi

        # Extract results
        SCORE=$(cat "${{ inputs.output }}/scan.json" | jq -r '.summary.score')
        VIOLATIONS=$(cat "${{ inputs.output }}/scan.json" | jq -r '.summary.totalViolations')

        echo "score=$SCORE" >> $GITHUB_OUTPUT
        echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
        echo "report=${{ inputs.output }}/scan.json" >> $GITHUB_OUTPUT

        # Check threshold
        if [ "$VIOLATIONS" -gt "${{ inputs.threshold }}" ]; then
          echo "::error::Accessibility check failed: $VIOLATIONS violations exceed threshold of ${{ inputs.threshold }}"
          exit 1
        fi

    - name: Generate report artifact
      shell: bash
      run: ally report -o "${{ inputs.output }}/ACCESSIBILITY.md"
